displayMainMenu:-
    
    write('#########################################################'),nl,
    write('#                                                       #'),nl,
    write('#     __         #   ##   ##  #     ##    ##     __     #') ,nl,
    write('#   \\/ o\\     #  #   ##   # # #     ##    ##    /o \\/   #'),nl,
    write('#   /\\__/     ####   ##   #  ##     ####  ##    \\__/\\   #'),nl,
    write('#                                                       #'),nl,
    write('#########################################################'),nl,
    write('#                                                       #'),nl,
    write('#              1 -  Single Player Easy                  #'),nl,
    write('#              2 -  Single Player Hard                  #'),nl,
    write('#              3 -     Multiplayer                      #'),nl,
    write('#              4 - Computer vs Computer                 #'),nl,
    write('#              5 -     How to play                      #'),nl,
    write('#              6 -        Exit                          #'),nl,
    write('#                                                       #'),nl,
    write('#########################################################'),nl
.

howToPlay:-
    
    write('#########################################################'),nl,
    write('#                                                       #'),nl,
    write('#     __         #   ##   ##  #     ##    ##     __     #') ,nl,
    write('#   \\/ o\\     #  #   ##   # # #     ##    ##    /o \\/   #'),nl,
    write('#   /\\__/     ####   ##   #  ##     ####  ##    \\__/\\   #'),nl,
    write('#                                                       #'),nl,
    write('#########################################################'),nl,
    write('#                                                       #'),nl,
    write('#     Jin Li is the Chinese word for Koi. Koi are       #'),nl,
    write('#    friendly fish. They love getting close to other    #'),nl,
    write('#         koi, rubbing up against each other,           #'),nl,
    write('#             gathering in small groups.                #'),nl,
    write('#                                                       #'),nl,
    write('#    In Jin Li the players each control two koi in a    #'),nl,
    write('#      pond. They swim their fish through the placid    #'),nl,
    write('#     water, maneuver around or jumping over stones     #'),nl,
    write('#   that are dropped into the pond, and score points    #'),nl,
    write('#     by getting close to any of the other koi. Be a    #'),nl,
    write('#   friendly koi and score points, but don\'t let your   #'),nl,
    write('#   opponent\'s koi get too friendly or you\'ll lose      #'),nl,
    write('#                        the game.                      #'),nl,
    write('#                                                       #'),nl,
    write('#         Each player have 10 stones and 2 Koi of       #'),nl,       
    write('#             the same color (red or yellow).           #'),nl,       
    write('#                                                       #'),nl,
    write('#      Each player\'s Koi start in the corner squares    #'),nl,   
    write('#                   closer to the player.               #'),nl,       
    write('#                                                       #'),nl,   
    write('#      Players take turns during the game moving        #'),nl,               
    write('#                      their Koi.                       #'),nl,                   
    write('#                                                       #'),nl,           
    write('#      On his turn, a player must do one of these       #'),nl,                       
    write('#                      two things:                      #'),nl,                       
    write('#                                                       #'),nl,               
    write('#            SWIM: A Koi SWIMS to an empty              #'),nl,                       
    write('#       square adjacent (ortogonaly or diagonaly)       #'),nl,                       
    write('#        to its current location. Then the player       #'),nl,                           
    write('#        takes one of his stones and places it in       #'),nl,                           
    write('#          any empty square on the board (DROP).        #'),nl,                                   
    write('#       If a player has run out of stones then he       #'),nl,                       
    write('#             does not DROP after a SWIM                #'),nl,                           
    write('#                                                       #'),nl,                   
    write('#         JUMP: A Koi jumps over one stone in an        #'),nl,                           
    write('#        adjacent square (ortogonaly or diagonaly)      #'),nl,               
    write('#           and lands on the empty square just          #'),nl,                   
    write('#         beyond the jumped stone. The jump must        #'),nl,                           
    write('#        be along a straight line and the Koi can       #'),nl,                               
    write('#         only jump over a single stone. When the       #'),nl,                           
    write('#            JUMP has been completed the player         #'),nl,                               
    write('#                   does not DROP a stone.              #'),nl,                               
    write('#                                                       #'),nl,
    write('#     After moving a Koi (and dropping a stone if       #'),nl,                   
    write('#   applicable), the player scores one point for each   #'),nl,                       
    write('#    other Koi adjacent to his Koi\'s new location. A    #'),nl,                           
    write('#   player may score 1, 2, or 3 points on a turn.       #'),nl,                               
    write('#                                                       #'),nl,
    write('#       The first player to score 10 points wins.       #'),nl,                                       
    write('#                                                       #'),nl,
    write('#########################################################'),nl,
    write('Press anything to continue...')
.
